### ISSUE TITLE
Starting Masternode not possible

### ISSUE THREAD

**Issue by Flitzpiep** [safedeal-project/safedeal#1]
I try to host a MN at ihostmn.com. The Dashboard from there schows, that the MN started but at the wallet is the MN-Status shown with "missing".

I opend a tiket at ihostmn.com: tiketnumber there is 18294. The support wrote: "our advice is to delete existing SFD--Masternode--1 and create new one with new collateral transaction (not exsisting one). " I created a new MN but nothing changed.

My adresses:
Masternode: SaLangHWsabzRT3rhYegqFTDHdxU1tFnqR with 3000SFD
Default: SfBZHNeeV1ezk1WDj56v2fNMFkvqVzopGZ with rd. 17SFD

I downloaded the wallet from GitHub:
Client VErsion: v2.1.0.0-ge8aaa67b8ca24093823cd1ad337f2078b36c8805

could you check please and advise what to do?

With best regardds,
André

**Comment by byrockkk** [comment]
What the solution was? It seems is closed already. I had the same issue and turned back to pool shared masternode.
